### PR TITLE
chore: update rule_schema.jsonc

### PR DESCRIPTION
**Pull request by cfabianski**
## Description

Ensure one and only cwe per rule

## Checklist

- [ ] I've added a snapshot that shows my rule works as expected.
- [ ] My rule has adequate metadata to explain its use.
- [ ] PR title follows [Conventional Commits](https://www.conventionalcommits.org/) format

### CODE REVIEW

**Comment by cfabianski** [comment]
Let's merge this one once we have done the job to only have 1 CWE per rule

**Comment by gotbadger** [comment]
@cfabianski Its at most 1 some might have zero

**Comment by cfabianski** [comment]
> @cfabianski Its at most 1 some might have zero

I don't think that's correct. We should always have a CWE

**Comment by gotbadger** [comment]
I was thinking of best practice type ones but looks like they can go under 693

**Comment by cfabianski** [comment]
Good to be merged once this is in https://github.com/Bearer/bearer-rules/pull/219

**Comment by gotbadger** [comment]
@cfabianski FYI https://github.com/Bearer/bearer/blob/26d4d746d72f63d51f2ba144f5e7e08e360ca400/internal/commands/process/settings/ruleValidator.go#L13 rules need to get released before this can merge to main

**Comment by gotbadger** [comment]
closed in favour of #296

**Pull request closed without merging**
